language: java
jdk:
- oraclejdk8
env:
  global:
    secure: ld0/WcH/Kl1C1/WDYULvUCdelavlbMFlA8qFLfS+LKAXEFt2AK0Fd+wdmMP1IPz1HSdrT/dYK8Sc5umvPv9hcMXUeCLjgVvYmfb8CxWReNkuRmzFmHznMIwU6D2kGr6Vbl92pa3qAmlqsPbZsmgdNrS8JXyrE93b08TTJpqft/YY3TNPlhlAXyj1FiBTyUV20crpxlq6VxHBcLbagMmjtnoYho+MoaeZ5IDExxOednTvxIAKy0X+7N77UhiZRP0A8CKJiTxi7PkSG2j2nQiGj0YR8apQFy6VFscwZWqLaiX/UAbcJFkdMR43IxokHJiaGlMY+UxYd4JOuRnGPkpqYAO14iOQmU5hzCqU+TReh7YP9xobOo8LQ2ZKqHvlNlcetcLM8Hi6hsPxvaOuyzXKYKhNeHz+owXv0KGLQOzFkAzd50Mzhh/KUuLWpD+XpQzG5qmomNvf8WtGH9tTPq8Mn3m3ltEFiLy1by13OKRbXTAe78vVKQsEy+UP5wJPwcbcwYgvyYHspu2Q3K4U5CsSqfsyZibCVOCjDkJwAVoOHTyZZ7ZkufU1vcmmnOpSySQTYQqTB75AbgP8/3nzmjBxK1OZoIfW0Q7BFjVz9GmVI9v/UJCONyQyfI5sAnVtSce120vAjLYUDdnIKZ0eEuaK7g+rIUcr+pAuh7kY5x1LAJM=
script: mvn package cf:push -Dcf.password=$PASSWORD
